language: node_js
node_js:
  - "13"

branches:
  only:
  - master

install:
  - npm install -g typescript
  - npm install --save-dev
  - npm run build
  - npm install 

script:
  - npm run test

cache:
  directories:
    - node_modules
